### ISSUE TITLE
Form heading qismi

### ISSUE THREAD

**Issue by mukhammadyn** [IlhomYuldoshev/Intro#1]
https://i.imgur.com/mOqsc4c.png
Shart bo'lmagan stillar bor ekan.
Bodyga berilgan font family butun saytga tasir qiladi. Shuning uchun textlarning font familysi body ga berilgan font family bilan bir xil bo'lsa, textga boshqatdan berish shart emas.

**Comment by IlhomYuldoshev** [comment]
ha chunarli
